---
title: "Consequences of Atmospheric Events<br>in the U.S.A."
author: "Felipe Campelo, Ph.D."
date: "December 17, 2014"
output: html_document
keep_md: TRUE
---

## Synopsis

## Data Processing

## Results

## Conclusions

### Appendix (to be removed): Assignment requirements

1. Mandatory sections: 
      - Synopsis
      - Data Processing
      - Results
      
2. All code must be shown

3. Figures: no less than one, no more than three.

4. Assignment description:  
      *Your data analysis must address the following questions:*
      
      - *Across the United States, which types of events (as indicated in the EVTYPE variable) are most           harmful with respect to population health?*
      
      - *Across the United States, which types of events have the greatest economic consequences?*
      
      *Consider writing your report as if it were to be read by a government or municipal manager who might be responsible for preparing for severe weather events and will need to prioritize resources for different types of events. However, there is no need to make any specific recommendations in your report.*